import "./globals.css";
import Link from "next/link";
import "bootstrap/dist/css/bootstrap.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let year = new Date();
  year = year.getFullYear();
  return (
    <html lang="en" style={{height:"100%"}}>
      <body style={{ minHeight: "100%" ,display:"flex", flexDirection:"column"}}>
        <header style={{ position: "fixed", width: "100%", zIndex: "1" }}>
          <nav className="navbar navbar-expand-lg">
            <div className="container">
              <Link className="navbar-brand text-white" href={"/"}>
                <i className="fa fa-graduation-cap fa-lg mr-2"></i>MY-BLOG
              </Link>
              <button
                className="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#nvbCollapse"
                aria-controls="nvbCollapse"
              >
                <span className="navbar-toggler-icon"></span>
              </button>
              <div 
                className="collapse navbar-collapse"
                id="nvbCollapse"
                style={{ justifyContent: "flex-end" ,zIndex:"5"}}
              >
                <ul
                  className="navbar-nav ml-auto"
                  style={{ display: "flex", gap: "15px" }}
                >
                  <li className="nav-item  pl-1">
                    <Link className="nav-link" href={"/blogs"}>
                      <i className="fa fa-th-list fa-fw mr-1"></i>BLOGS
                    </Link>
                  </li>
                  <li className="nav-item pl-1">
                    <Link className="nav-link" href={"/blogs/addblog"}>
                      <i className="fa fa-phone fa-fw fa-rotate-180 mr-1"></i>
                      ADD BLOG
                    </Link>
                  </li>
                  <li className="nav-item pl-1">
                    <Link className="nav-link" href={"/aboutme"}>
                      <i className="fa fa-home fa-fw mr-1"></i>ABOUT
                    </Link>
                  </li>
                  <li className="nav-item pl-1">
                    <Link className="nav-link" href={"/#footer"}>
                      <i className="fa fa-info-circle fa-fw mr-1"></i>CONTACT
                    </Link>
                  </li>
                  
                  {/* <li className="nav-item pl-1">
                  <Link className="nav-link" href={"logout"}>
                    <i className="fa fa-user-plus fa-fw mr-1"></i>LOG OUT
                  </Link>
                </li> */}
                </ul>
              </div>
            </div>
          </nav>
        </header>
        {children}
        <footer id="footer" >
          <div 
            className="jumbotron jumbotron-fluid bg-secondary p-4 mt-5 mb-0 "
            id="footer-div"
          >
            <div className="container">
              <div className="row">
                <div className="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4 cizgi">
                  <div className="card bg-secondary border-0">
                    <div className="card-body text-light text-center">
                      <h5
                        className="card-title text-white display-4"
                        style={{ fontSize: "20px" }}
                      >
                        MADE BY
                      </h5>
                      <p className="d-inline lead">
                        Bhushan Patil © {year}
                        <br />
                        <Link href={"/"} className="text-light d-block lead">
                          Blog
                        </Link>
                      </p>
                    </div>
                  </div>
                </div>

                <div className="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 cizgi">
                  <div className="card bg-secondary border-0">
                    <div className="card-body text-center">
                      <h5
                        className="card-title text-white display-4"
                        style={{ fontSize: "20px" }}
                      >
                        CONTACT US
                      </h5>
                      <Link
                        className="text-light d-block lead"
                        // style={{ marginLeft: "-20px" }}
                        href={"/"}
                      >
                        <i className="fa fa-phone mr-2"></i>+91 1234567890
                      </Link>
                      <Link className="text-light d-block lead" href={"#"}>
                        <i className="fa fa-envelope mr-2"></i>
                        admin@localhost.com
                      </Link>
                    </div>
                  </div>
                </div>

                <div className="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 ">
                  <div className="card bg-secondary border-0">
                    <div className="card-body text-center">
                      <h5
                        className="card-title text-white display-4"
                        style={{ fontSize: "20px" }}
                      >
                        SOCIAL MEDIA
                      </h5>

                      <Link className="text-light" href={"#"}>
                        <i className="fa fa-facebook-square fa-fw fa-2x"></i>
                      </Link>

                      <Link className="text-light" href={"#"}>
                        <i className="fa fa-twitter-square fa-fw fa-2x"></i>
                      </Link>

                      <Link className="text-light" href={"#"}>
                        <i className="fa fa-instagram fa-fw fa-2x"></i>
                      </Link>

                      <Link className="text-light" href={"#"}>
                        <i className="fa fa-linkedin fa-fw fa-2x"></i>
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
