import "./globals.css";
import Link from "next/link";
import "bootstrap/dist/css/bootstrap.css";
import Navbar from "@/component/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let year = new Date();
  year = year.getFullYear();
  return (
    <html lang="en" style={{ height: "100%" }}>
      <body
        style={{ minHeight: "100%", display: "flex", flexDirection: "column" }}
      >
      <Navbar/>
        {children}
        <footer id="footer">
          <div
            className="jumbotron jumbotron-fluid bg-secondary p-4 mt-5 mb-0 "
            id="footer-div"
          >
            <div className="container">
              <div className="row">
                <div className="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4 cizgi">
                  <div className="card bg-secondary border-0">
                    <div className="card-body text-light text-center">
                      <h5
                        className="card-title text-white display-4"
                        style={{ fontSize: "20px" }}
                      >
                        MADE BY
                      </h5>
                      <p className="d-inline lead">
                        Bhushan Patil © {year}
                        <br />
                        <Link href={"/"} className="text-light d-block lead">
                          Blog
                        </Link>
                      </p>
                    </div>
                  </div>
                </div>

                <div className="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 cizgi">
                  <div className="card bg-secondary border-0">
                    <div className="card-body text-center">
                      <h5
                        className="card-title text-white display-4"
                        style={{ fontSize: "20px" }}
                      >
                        CONTACT US
                      </h5>
                      <Link
                        className="text-light d-block lead"
                        // style={{ marginLeft: "-20px" }}
                        href={"/"}
                      >
                        <i className="fa fa-phone mr-2"></i>+91 1234567890
                      </Link>
                      <Link className="text-light d-block lead" href={"#"}>
                        <i className="fa fa-envelope mr-2"></i>
                        admin@localhost.com
                      </Link>
                    </div>
                  </div>
                </div>

                <div className="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 ">
                  <div className="card bg-secondary border-0">
                    <div className="card-body text-center">
                      <h5
                        className="card-title text-white display-4"
                        style={{ fontSize: "20px" }}
                      >
                        SOCIAL MEDIA
                      </h5>

                      <Link className="text-light" href={"#"}>
                        <i className="fa fa-facebook-square fa-fw fa-2x"></i>
                      </Link>

                      <Link className="text-light" href={"#"}>
                        <i className="fa fa-twitter-square fa-fw fa-2x"></i>
                      </Link>

                      <Link className="text-light" href={"#"}>
                        <i className="fa fa-instagram fa-fw fa-2x"></i>
                      </Link>

                      <Link className="text-light" href={"#"}>
                        <i className="fa fa-linkedin fa-fw fa-2x"></i>
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
